vp parmar

diff --git a/Jenkinsfile-buld b/Jenkinsfile-buld
--- a/Jenkinsfile-buld
+++ b/Jenkinsfile-buld
@@ -54,13 +54,31 @@ pipeline {
             }
         }
 
-      stage('Run Docker Container') {
-    steps {
-        script {
-            echo 'Stopping old Docker container if it exists...'
-            sh '''
-                docker ps -q --filter "name=${DOCKER_IMAGE}" | xargs -r docker stop
-                docker ps -a -q --filter "name=${DOCKER_IMAGE}" | xargs -r docker rm
+        stage('Run Docker Container') {
+            steps {
+                script {
+                    echo 'Stopping old Docker container if it exists...'
+                    sh '''
+                        docker ps -q --filter "name=${DOCKER_IMAGE}" | xargs -r docker stop
+                        docker ps -a -q --filter "name=${DOCKER_IMAGE}" | xargs -r docker rm
+                    '''
+                    echo 'Running new Docker container...'
+                    sh '''
+                        docker run -d -p ${APP_PORT}:${APP_PORT} --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:${DOCKER_TAG}
+                    '''
+                    echo 'Verifying Docker container status...'
+                    sh '''
+                        if ! docker ps --filter "name=${DOCKER_IMAGE}" --format "{{.Names}}" | grep -q "^${DOCKER_IMAGE}$"; then
+                            echo "Error: Docker container failed to start."
+                            exit 1
+                        fi
+                    '''
+                    echo 'Waiting for Docker container logs...'
+                    sleep time: 10, unit: 'SECONDS'
+                    sh 'docker logs ${DOCKER_IMAGE}'
+                }
+            }
+        }
 
         stage('Test Flask App') {
             steps {
