build file update

diff --git a/Jenkinsfile-buld b/Jenkinsfile-buld
--- a/Jenkinsfile-buld
+++ b/Jenkinsfile-buld
@@ -7,12 +7,12 @@ pipeline {
     }
 
     environment {
-        APP_PORT = '5000'  // Flask app port
-        APP_URL = "http://localhost:%APP_PORT%"  // URL to access the app
+        APP_PORT = '5000' // Flask app port
+        APP_URL = "http://localhost:%APP_PORT%" // URL to access the app
     }
 
     triggers {
-        githubPush()  // Automatically trigger on GitHub push
+        githubPush() // Automatically trigger on GitHub push
     }
 
     stages {
@@ -20,7 +20,9 @@ pipeline {
             steps {
                 script {
                     echo 'Building Docker image...'
-                    bat "docker build -t %DOCKER_IMAGE%:%DOCKER_TAG% ."
+                    bat """
+                    docker build -t %DOCKER_IMAGE%:%DOCKER_TAG% .
+                    """
                 }
             }
         }
@@ -29,16 +31,20 @@ pipeline {
             steps {
                 script {
                     echo 'Stopping and removing any previous containers using the port...'
-                    bat '''
-                    for /F "tokens=*" %%i in ('docker ps -q --filter "publish=%APP_PORT%"') do docker stop %%i || echo "No containers to stop."
-                    for /F "tokens=*" %%i in ('docker ps -a -q --filter "publish=%APP_PORT%"') do docker rm %%i || echo "No containers to remove."
-                    '''
+                    bat """
+                    for /F "tokens=*" %%i in ('docker ps -q --filter "ancestor=%DOCKER_IMAGE%') do docker stop %%i || echo "No containers to stop."
+                    for /F "tokens=*" %%i in ('docker ps -a -q --filter "ancestor=%DOCKER_IMAGE%') do docker rm %%i || echo "No containers to remove."
+                    """
 
                     echo 'Running new Docker container...'
-                    bat "docker run -d -p %APP_PORT%:%APP_PORT% --name %DOCKER_IMAGE% %DOCKER_IMAGE%:%DOCKER_TAG%"
+                    bat """
+                    docker run -d -p %APP_PORT%:%APP_PORT% --name %DOCKER_IMAGE% %DOCKER_IMAGE%:%DOCKER_TAG%
+                    """
 
                     echo 'Waiting for Docker container logs...'
                     sleep time: 10, unit: 'SECONDS'
+
+                    echo 'Displaying Docker container logs:'
                     bat "docker logs %DOCKER_IMAGE%"
                 }
             }
@@ -77,9 +83,11 @@ pipeline {
             echo 'Deploy pipeline completed successfully!'
         }
         failure {
-            echo 'Deploy pipeline failed. Please check the logs for more details.'
-            echo 'Showing container logs for debugging...'
-            bat "docker logs %DOCKER_IMAGE%"
+            script {
+                echo 'Deploy pipeline failed. Please check the logs for more details.'
+                echo 'Showing container logs for debugging...'
+                bat "docker logs %DOCKER_IMAGE%"
+            }
         }
     }
 }
